# Домашнее задание «Библиотека numpy. Вычислительные задачи»


In [1]:
import numpy as np

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
N = 42
np.arange(N, -1, -1)

array([42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [20]:
N = 11
diag_matrix = np.diag(np.arange(N, -1, -1))
print(diag_matrix)
diag_matrix.diagonal().sum()

[[11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]


66

## Задание 3
Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [46]:
coefs = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
ordinate = np.array([4, 12, -3])
x, y, z = np.linalg.solve(coefs, ordinate) #.astype(int)
print(f'x: {x}, y: {y}, z: {z}')


x: 0.4666666666666668, y: 3.844444444444444, z: -5.555555555555555


## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем: `users_stats`

На сайт заходит очередной посетитель, о покупках которого известно следующее: `next_user_stats`

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats



In [107]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    return np.dot( a, b ) / ( aLength * bLength )

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

f = lambda u: cosine(next_user_stats, u)
closest_index = np.arccos(np.apply_along_axis(f, 1, users_stats)).argmin()

print(f'The closest user is the {closest_index+1}th user: {users_stats[closest_index]}')  

The closest user is the 8th user: [0 1 1 0 0 0]
